---
metrics_group_server: "Metrics Server"
metrics_group_hosts: "Metrics Hosts"
metrics_servers: 
  - "rhel"
metrics_hosts:
  - "rhel2"
  - "rhel3"
metrics_hosts_variables:
  metrics_retention_days: 7

  firewall:
    - service: pmcd
      state: enabled
    - service: cockpit
      state: enabled
metrics_server_variables:
  metrics_graph_service: yes
  metrics_query_service: yes
  metrics_retention_days: 7
  metrics_monitored_hosts: "{{ groups['all'] }}"
  firewall:
    - service: grafana
      state: enabled
    - service: cockpit
      state: enabled
