---
- name: Playbook to configure AAP
  hosts: all
  connection: local
  # vars:
  #   validate_certs: "{{ ssl_check }}"
  #   controller_username: '{{ username }}'
  #   controller_password: '{{ password }}'
  vars_files:
    - "../group_vars/project.yml"
    - "../group_vars/main.yml"
    - "../group_vars/inventory.yml"
    - "../group_vars/hosts.yml"
  tasks:
    
    - name: Create a new project
      awx.awx.project:
        name: "{{ project_name }}"
        organization: "{{ project_organization }}"
        scm_type: "{{ project_type }}"
        #scm_url: "{{ project_github_url }}"
        local_path: "{{ project_local_path }}"
        update_project: yes
        state: present
        validate_certs: "{{ ssl_check }}"
        controller_username: '{{ username }}'
        controller_password: '{{ password }}'
    
    - name: Create inventory
      awx.awx.inventory:
        name: "{{ inventory_name }}"
        organization: "{{ inventory_org }}"
        state: present
        validate_certs: "{{ ssl_check }}"
        controller_username: '{{ username }}'
        controller_password: '{{ password }}'
    
    - name: Create hosts
      awx.awx.host:
        name: "{{ item }}"
        inventory: "{{ inventory_name }}"
        state: present
        validate_certs: "{{ ssl_check }}"
        controller_username: '{{ username }}'
        controller_password: '{{ password }}'
      loop: "{{ rhel_hosts }}"

    - name: Fetch private key
      slurp:
        src: "{{ private_ssh_key_path }}"
      register: ssh_key

    - name: Add SSH key Credential
      awx.awx.credential:
        name: acme_ssh_key
        validate_certs: "{{ ssl_check }}"
        controller_username: '{{ username }}'
        controller_password: '{{ password }}'
        organization: "{{ inventory_org }}"
        state: present
        credential_type: Machine
        inputs:
          username: root
          ssh_key_data: "{{ ssh_key['content'] | b64decode }}"
        