---
- name: Playbook to configure AAP
  hosts: all
  connection: local
  # vars:
  #   tower_verify_ssl: "{{ ssl_check }}"
  #   controller_username: '{{ username }}'
  #   controller_password: '{{ password }}'
  vars_files:
    - "../group_vars/project.yml"
    - "../group_vars/main.yml"
    - "../group_vars/inventory.yml"
  tasks:
    
    - name: Create a new project
      awx.awx.project:
        name: "{{ project_name }}"
        organization: "{{ project_organization }}"
        scm_type: "{{ project_type }}"
        scm_url: "{{ project_github_url }}"
        update_project: yes
        state: present
        validate_certs: "{{ ssl_check }}"
        controller_username: '{{ username }}'
        controller_password: '{{ password }}'
    
    - name: Create inventory
      awx.awx.inventory:
        name: "{{ inventory_name }}"
        organization: "{{ inventory_org }}"
        state: present
        validate_certs: "{{ ssl_check }}"
        controller_username: '{{ username }}'
        controller_password: '{{ password }}'
    
    - name: Create hosts
      awx.awx.host:
        name: "{{ rhel_hosts }}"
        inventory: "{{ inventory_name }}"
        state: present
        validate_certs: "{{ ssl_check }}"
        controller_username: '{{ username }}'
        controller_password: '{{ password }}'