---
- name: Get a license for AAP.
  hosts: all
  tasks:
    - name: License AAP
      awx.awx.license:
        validate_certs: no
        manifest: "/root/manifest_instruqt_aap_20220927T195338Z.zip"
        controller_username: rhel
        controller_password: redhat
        force: yes
