---
- name: Get a license for AAP.
  hosts: all
  tasks:
    - name: License AAP
      awx.awx.license:
        validate_certs: no
        manifest: "{{ manifest_file_and_path }}"
        controller_username: rhel
        controller_password: redhat
        force: yes
