---
- name: Get a license for AAP.
  hosts: all
  vars_files:
    - "../group_vars/main.yml"
  tasks:
    - name: License AAP
      awx.awx.license:
        validate_certs: no
        manifest: "{{ manifest_file_and_path }}"
        controller_username: "{{ username }}"
        controller_password: "{{ password }}"
        force: yes
