---
- name: Setup the playbook.
  hosts: all
  connection: local
  vars_files:
    - "../group_vars/groups.yml"
    - "../group_vars/inventory.yml"
    - "../group_vars/main.yml"
  tasks:
    - name: Setup Metrics Server group
      awx.awx.group:
        name: "{{ metrics_group_server }}"
        #preserve_existing_hosts: yes
        state: present
        inventory: "{{ inventory_name }}"
        hosts: "{{ metrics_servers }}"
        validate_certs: "{{ ssl_check }}"
        controller_username: '{{ username }}'
        controller_password: '{{ password }}'
        variables: "{{ metrics_server_variables }}"
    - name: Setup Metrics Hosts group
      awx.awx.group:
        name: "{{ metrics_group_hosts }}"
        #preserve_existing_hosts: yes
        state: present
        inventory: "{{ inventory_name }}"
        hosts: "{{ metrics_hosts }}"
        validate_certs: "{{ ssl_check }}"
        controller_username: '{{ username }}'
        controller_password: '{{ password }}'
        variables: "{{ metrics_hosts_variables }}"
    - name: Setup "Production Hosts" inventory
      awx.awx.inventory:
        name: "{{ inventory_name }}"
        organization: "{{ inventory_org }}"
        state: present
        validate_certs: "{{ ssl_check }}"
        controller_username: '{{ username }}'
        controller_password: '{{ password }}'
        variables: "{{ inventory_variables }}"